###Registro de usuario
POST http://localhost:3000/api/auth/registro
content-type: application/json

{
    "nombre_usuario": "usuario2",
    "nombre": "usuario",
    "apellido": "apellido",
    "numero": "0988851126",
    "carrera": "carrera",
    "correo": "DxwWtw@example.com",
    "institucion": "universidad",
    "password": "123456"
}

###Inicio de sesion
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "nombre_usuario": "alexitotn21",
    "password": "123333"
}


###Registrarse con google (No enviar aqui probar en el navegador)
GET http://localhost:3000/api/auth/google


###Obtener el perfil del usuario
GET http://localhost:3000/api/auth/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywibm9tYnJlIjoiQWxleCAiLCJhcGVsbGlkbyI6IlRvbmF0byIsInJvbCI6ImNsaWVudGUiLCJjb3JyZW8iOiJhbGV4aXRvdG4yMUBnbWFpbC5jb20iLCJpYXQiOjE3Mzc0OTI1MjIsImV4cCI6MTczNzU3ODkyMn0.EAkcUNxzlw11TFXU0iqjOjvIcopr3SDO_uAWx4rMwLc