###Obtener todos los comprobantes
GET http://localhost:3000/api/comprobante

###Obtener comprobante por tarea
GET http://localhost:3000/api/comprobante/tarea/5

###Actualizar comprobante
PUT http://localhost:3000/api/comprobante/2
content-type: application/json

{
    "estado_comprobante": "Rechazado",
    "comentario":"Esto es un comentario"
}