###Obtener todas las tareas
GET http://localhost:3000/api/tareas


###Obtener tareas por estado (En Revisión, Aprobada, En Progreso, Finalizado)
GET http://localhost:3000/api/tareas/estado/Aprobada


###Obtener tarea por usuario
GET http://localhost:3000/api/tareas/usuario/4

###Obtener el total de tareas por estado
GET http://localhost:3000/api/tareas/totales

###Buscar tareas por nombre
GET http://localhost:3000/api/tareas/buscar/Tarea Ciencias

###Actualizar tarea
PUT http://localhost:3000/api/tareas/3
content-type: application/json

{
    "estado": "En Progreso"
}