###Obtener todos los usuarios
GET http://localhost:3000/api/usuario

###Obtener un usuario
GET http://localhost:3000/api/usuario/7
### Para crear un nuevo usuario se hace desde el auth

###Actualizar un usuario
PUT http://localhost:3000/api/usuario/7
content-type: application/json

{
    "password": "123333"
}